
#include <stdint.h>
enum {
    FLAG_DEBUG = 0,
    FLAG_LOG = 1,
    FLAG_ERR = 2,
    FLAG_DEBUG_CAMERA_STREAM_LOOP = 3,
    FLAG_IPC = 4
};

#define MASK_DEBUG (1U << FLAG_DEBUG)
#define MASK_LOG (1U << FLAG_LOG)
#define MASK_ERR (1U << FLAG_ERR)
#define MASK_DEBUG_CAMERA_STREAM_LOOP (1U << FLAG_DEBUG_CAMERA_STREAM_LOOP)
#define MASK_IPC (1U << FLAG_IPC)

#define DEBUG_MODE MASK_DEBUG
#define DEBUG_CAMERA_STREAM MASK_DEBUG_CAMERA_STREAM_LOOP
#define IPC_REQUIRED MASK_IPC

extern uint32_t OPTIONS_MASK;
